# Generated by Django 5.1.6 on 2025-03-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_verified_user_verified_at_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiccode',
            name='code',
            field=models.CharField(max_length=5),
        ),
    ]
